{% set version = "2.9.2" %}

package:
    name: tkdnd
    version: {{ version }}

source:
    git_url: https://github.com/petasis/tkdnd.git
    git_rev: tkdnd-release-test-v{{ version }}

build:
    number: 0

requirements:
    build:
        #- {{ compiler('c') }}
        - python 3.7
        - tk 8.6.*
        - cmake
        - vc 14            # [win64]

    run:
        - python 3.7
        - tk 8.6.*
        - vs2015_runtime   # [win64]
#test:
#    imports:
#        - Pmw

about:
    description: TkDND is an extension that adds native drag & drop capabilities to the Tk toolkit
    home: https://sourceforge.net/projects/tkdnd/
    license: MIT
