{% set version = "2.9.2" %}

package:
    name: tkdnd
    version: {{ version }}

source:
    git_url: https://github.com/petasis/tkdnd.git
    git_rev: tkdnd-release-test-v{{ version }}

build:
    number: 1

requirements:
    build:
      - tk 8.6.8
      - cmake
      - vc 14            # [win64]
      # - {{ compiler('c') }}                # [linux]
      # - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
      # - {{ cdt('libx11-devel') }}          # [linux]
      # - {{ cdt('libxcb') }}                # [linux]
      # - {{ cdt('libxau') }}                # [linux]
      # - {{ cdt('libxext') }}                # [linux]


    run:
      - tk 8.6.*
      - vs2015_runtime   # [win64]

about:
  summary: 'TkDND is an extension that adds native drag & drop capabilities to the Tk toolkit'
  description: TkDND is an extension that adds native drag & drop capabilities to the Tk toolkit
  home: https://github.com/petasis/tkdnd
  license: MIT
